# Generated by Django 3.2.3 on 2021-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='votes_to_skip',
            new_name='answersRequired',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='guest_can_pause',
            new_name='exampleBoolean',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='host',
            new_name='name',
        ),
    ]
